# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.
# API specification



#Salesforce Configurations    
sfdc:
   
  token: "![acs1tGIyNy8hXNlLXSdiuFgolKQkiGs1ZD7UcfmR4Ns=]"
  password : "![7M4iZ7XsCsuxeE7910IoTg==]"
    